[package]
name = "powers7"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = "0.4.0"
casecsv = { path = "../casecsv" }
sparsetools = { path = "../sparsetools" }
itertools = "0.11"
anyhow = "1"
